## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file trigonometrie.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_140 = Integer(140); _sage_const_1 = Integer(1); _sage_const_143 = Integer(143); _sage_const_145 = Integer(145); _sage_const_0 = Integer(0); _sage_const_150 = Integer(150); _sage_const_180 = Integer(180); _sage_const_183 = Integer(183); _sage_const_185 = Integer(185); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_188 = Integer(188); _sage_const_215 = Integer(215); _sage_const_218 = Integer(218); _sage_const_220 = Integer(220); _sage_const_231 = Integer(231)## This file (trigonometrie.sagetex.sage) was *autogenerated* from trigonometrie.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('trigonometrie', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_140 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_143 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_0 , latex(f(x)))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_1 , latex(g(x)))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_150 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(f(x), x, -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_150 )
_st_.current_tex_line = _sage_const_180 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_183 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_185 
 _st_.inline(_sage_const_2 , latex(f(x)))
except:
 _st_.goboom(_sage_const_185 )
try:
 _st_.current_tex_line = _sage_const_185 
 _st_.inline(_sage_const_3 , latex(F(x)))
except:
 _st_.goboom(_sage_const_185 )
try:
 _st_.current_tex_line = _sage_const_188 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(F(x), x, _sage_const_0 , pi))
except:
 _st_.goboom(_sage_const_188 )
try:
 _st_.current_tex_line = _sage_const_215 
 _st_.commandline(_sage_const_0 , r"""
  sage: factor(x^2 + 2*x + 1)
#  (x + 999)^2
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_218 )
try:
 _st_.current_tex_line = _sage_const_220 
 _st_.commandline(_sage_const_1 , r"""
sage: h = cos(x)^6 + sin(x)^6 + 3 * sin(x)^2 * cos(x)^2; h
sin(x)^6 + cos(x)^6 + 3*sin(x)^2*cos(x)^2
La même après avoir configuré les affichages en latex:

#sage: %display latex
sage: h
Simplifions-la:

sage: h.simplify_trig()
1
""", globals(), locals(), True)
except:
 _st_.goboom(_sage_const_231 )
_st_.endofdoc()

