## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file trigonometrie-fonction-sin.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_155 = Integer(155); _sage_const_159 = Integer(159); _sage_const_163 = Integer(163); _sage_const_0 = Integer(0); _sage_const_180 = Integer(180); _sage_const_1 = Integer(1); _sage_const_191 = Integer(191); _sage_const_195 = Integer(195); _sage_const_206 = Integer(206); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_210 = Integer(210); _sage_const_211 = Integer(211); _sage_const_212 = Integer(212); _sage_const_4 = Integer(4); _sage_const_226 = Integer(226); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_248 = Integer(248); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_256 = Integer(256); _sage_const_260 = Integer(260); _sage_const_267 = Integer(267); _sage_const_20 = Integer(20); _sage_const_285 = Integer(285); _sage_const_9 = Integer(9); _sage_const_10 = Integer(10); _sage_const_297 = Integer(297); _sage_const_11 = Integer(11); _sage_const_12 = Integer(12); _sage_const_300 = Integer(300); _sage_const_301 = Integer(301); _sage_const_302 = Integer(302)## This file (trigonometrie-fonction-sin.sagetex.sage) was *autogenerated* from trigonometrie-fonction-sin.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('trigonometrie-fonction-sin', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_155 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(sin(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_159 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_163 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot(sin(x), x, -pi, pi))
except:
 _st_.goboom(_sage_const_163 )
try:
 _st_.current_tex_line = _sage_const_180 
 _st_.inline(_sage_const_0 , latex(f(x)))
except:
 _st_.goboom(_sage_const_180 )
try:
 _st_.current_tex_line = _sage_const_180 
 _st_.inline(_sage_const_1 , latex(F(x)))
except:
 _st_.goboom(_sage_const_180 )
_st_.current_tex_line = _sage_const_191 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(arcsin(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_195 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_206 
 _st_.inline(_sage_const_2 , latex(f(x)))
except:
 _st_.goboom(_sage_const_206 )
try:
 _st_.current_tex_line = _sage_const_206 
 _st_.inline(_sage_const_3 , latex(g(x)))
except:
 _st_.goboom(_sage_const_206 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot(f(x), x, -_sage_const_1 , _sage_const_1 ))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_211 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=plot(sin(x), x, -pi/_sage_const_2 , pi/_sage_const_2 ))
except:
 _st_.goboom(_sage_const_211 )
try:
 _st_.current_tex_line = _sage_const_212 
 _st_.inline(_sage_const_4 , latex(f(x)))
except:
 _st_.goboom(_sage_const_212 )
try:
 _st_.current_tex_line = _sage_const_226 
 _st_.inline(_sage_const_5 , latex(f(x)))
except:
 _st_.goboom(_sage_const_226 )
try:
 _st_.current_tex_line = _sage_const_226 
 _st_.inline(_sage_const_6 , latex(F(x)))
except:
 _st_.goboom(_sage_const_226 )
try:
 _st_.current_tex_line = _sage_const_248 
 _st_.inline(_sage_const_7 , latex(f(x)))
except:
 _st_.goboom(_sage_const_248 )
try:
 _st_.current_tex_line = _sage_const_248 
 _st_.inline(_sage_const_8 , latex(F(x)))
except:
 _st_.goboom(_sage_const_248 )
_st_.current_tex_line = _sage_const_256 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(arcsinh(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_260 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_267 
 _st_.plot(_sage_const_3 , format='notprovided', _p_=plot(arcsinh(x), x, -_sage_const_20 , _sage_const_20 ))
except:
 _st_.goboom(_sage_const_267 )
try:
 _st_.current_tex_line = _sage_const_285 
 _st_.inline(_sage_const_9 , latex(f(x)))
except:
 _st_.goboom(_sage_const_285 )
try:
 _st_.current_tex_line = _sage_const_285 
 _st_.inline(_sage_const_10 , latex(g(x)))
except:
 _st_.goboom(_sage_const_285 )
try:
 _st_.current_tex_line = _sage_const_297 
 _st_.inline(_sage_const_11 , latex(f(x)))
except:
 _st_.goboom(_sage_const_297 )
try:
 _st_.current_tex_line = _sage_const_297 
 _st_.inline(_sage_const_12 , latex(F(x)))
except:
 _st_.goboom(_sage_const_297 )
try:
 _st_.current_tex_line = _sage_const_300 
 _st_.plot(_sage_const_4 , format='notprovided', _p_=plot(f(x), x, -_sage_const_20 , _sage_const_20 ))
except:
 _st_.goboom(_sage_const_300 )
try:
 _st_.current_tex_line = _sage_const_301 
 _st_.plot(_sage_const_5 , format='notprovided', _p_=plot(g(x), x, -_sage_const_20 , _sage_const_20 ))
except:
 _st_.goboom(_sage_const_301 )
try:
 _st_.current_tex_line = _sage_const_302 
 _st_.plot(_sage_const_6 , format='notprovided', _p_=plot(F(x), x, -_sage_const_20 , _sage_const_20 ))
except:
 _st_.goboom(_sage_const_302 )
_st_.endofdoc()

