## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file trigonometrie01.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_159 = Integer(159); _sage_const_1 = Integer(1); _sage_const_162 = Integer(162); _sage_const_164 = Integer(164); _sage_const_0 = Integer(0); _sage_const_188 = Integer(188); _sage_const_191 = Integer(191); _sage_const_193 = Integer(193); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_216 = Integer(216); _sage_const_219 = Integer(219); _sage_const_221 = Integer(221); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_249 = Integer(249); _sage_const_252 = Integer(252); _sage_const_254 = Integer(254); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_281 = Integer(281); _sage_const_284 = Integer(284); _sage_const_286 = Integer(286); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_320 = Integer(320); _sage_const_323 = Integer(323); _sage_const_325 = Integer(325); _sage_const_10 = Integer(10); _sage_const_11 = Integer(11); _sage_const_359 = Integer(359); _sage_const_362 = Integer(362); _sage_const_364 = Integer(364); _sage_const_12 = Integer(12); _sage_const_13 = Integer(13); _sage_const_391 = Integer(391); _sage_const_394 = Integer(394); _sage_const_396 = Integer(396); _sage_const_14 = Integer(14); _sage_const_15 = Integer(15)## This file (trigonometrie01.sagetex.sage) was *autogenerated* from trigonometrie01.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('trigonometrie01', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_159 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_162 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_164 
 _st_.inline(_sage_const_0 , latex(f(x)))
except:
 _st_.goboom(_sage_const_164 )
try:
 _st_.current_tex_line = _sage_const_164 
 _st_.inline(_sage_const_1 , latex(g(x)))
except:
 _st_.goboom(_sage_const_164 )
_st_.current_tex_line = _sage_const_188 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_191 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_193 
 _st_.inline(_sage_const_2 , latex(f(x)))
except:
 _st_.goboom(_sage_const_193 )
try:
 _st_.current_tex_line = _sage_const_193 
 _st_.inline(_sage_const_3 , latex(F(x)))
except:
 _st_.goboom(_sage_const_193 )
_st_.current_tex_line = _sage_const_216 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(asin(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_219 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_221 
 _st_.inline(_sage_const_4 , latex(f(x)))
except:
 _st_.goboom(_sage_const_221 )
try:
 _st_.current_tex_line = _sage_const_221 
 _st_.inline(_sage_const_5 , latex(g(x)))
except:
 _st_.goboom(_sage_const_221 )
_st_.current_tex_line = _sage_const_249 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(asin(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_252 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_254 
 _st_.inline(_sage_const_6 , latex(f(x)))
except:
 _st_.goboom(_sage_const_254 )
try:
 _st_.current_tex_line = _sage_const_254 
 _st_.inline(_sage_const_7 , latex(F(x)))
except:
 _st_.goboom(_sage_const_254 )
_st_.current_tex_line = _sage_const_281 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(atan(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_284 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_286 
 _st_.inline(_sage_const_8 , latex(f(x)))
except:
 _st_.goboom(_sage_const_286 )
try:
 _st_.current_tex_line = _sage_const_286 
 _st_.inline(_sage_const_9 , latex(g(x)))
except:
 _st_.goboom(_sage_const_286 )
_st_.current_tex_line = _sage_const_320 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(atan(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_323 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_10 , latex(f(x)))
except:
 _st_.goboom(_sage_const_325 )
try:
 _st_.current_tex_line = _sage_const_325 
 _st_.inline(_sage_const_11 , latex(F(x)))
except:
 _st_.goboom(_sage_const_325 )
_st_.current_tex_line = _sage_const_359 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(ln(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_362 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_364 
 _st_.inline(_sage_const_12 , latex(f(x)))
except:
 _st_.goboom(_sage_const_364 )
try:
 _st_.current_tex_line = _sage_const_364 
 _st_.inline(_sage_const_13 , latex(g(x)))
except:
 _st_.goboom(_sage_const_364 )
_st_.current_tex_line = _sage_const_391 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(ln(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_394 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_396 
 _st_.inline(_sage_const_14 , latex(f(x)))
except:
 _st_.goboom(_sage_const_396 )
try:
 _st_.current_tex_line = _sage_const_396 
 _st_.inline(_sage_const_15 , latex(F(x)))
except:
 _st_.goboom(_sage_const_396 )
_st_.endofdoc()

