## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file trigonometrie.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_140 = Integer(140); _sage_const_1 = Integer(1); _sage_const_143 = Integer(143); _sage_const_145 = Integer(145); _sage_const_0 = Integer(0); _sage_const_169 = Integer(169); _sage_const_172 = Integer(172); _sage_const_174 = Integer(174); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3)## This file (trigonometrie.sagetex.sage) was *autogenerated* from trigonometrie.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('trigonometrie', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_140 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); g = symbolic_expression(diff(f(x),x,_sage_const_1 )).function(x)
except:
 _st_.goboom(_sage_const_143 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_0 , latex(f(x)))
except:
 _st_.goboom(_sage_const_145 )
try:
 _st_.current_tex_line = _sage_const_145 
 _st_.inline(_sage_const_1 , latex(g(x)))
except:
 _st_.goboom(_sage_const_145 )
_st_.current_tex_line = _sage_const_169 
_st_.blockbegin()
try:
     __tmp__=var("x"); f = symbolic_expression(acos(x)).function(x)
     __tmp__=var("x"); F = symbolic_expression(integrate(f(x),x)).function(x)
except:
 _st_.goboom(_sage_const_172 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_174 
 _st_.inline(_sage_const_2 , latex(f(x)))
except:
 _st_.goboom(_sage_const_174 )
try:
 _st_.current_tex_line = _sage_const_174 
 _st_.inline(_sage_const_3 , latex(F(x)))
except:
 _st_.goboom(_sage_const_174 )
_st_.endofdoc()

